import {
  AlertTriangle,
  BadgeCheck,
  FileSearch,
  SearchCheck,
} from "lucide-react";
import type {
  GlobalSettings,
  RedirectRule,
  RolePermission,
  SeoPage,
  SitemapState,
  SummaryCardData,
} from "./types";

export const initialPages: SeoPage[] = [
  {
    id: "page-1",
    name: "Home",
    url: "/",
    status: "complete",
    indexed: true,
    metaTitle: "Industrial Roller Manufacturer in India | Indian Roller",
    metaDescription:
      "Explore engineered industrial rollers with precision finishing and fast delivery.",
    keywords: "industrial rollers, rubber rollers, india roller",
    canonicalUrl: "https://indianroller.com/",
    robots: "index, follow",
    openGraphTitle: "Indian Roller | Precision Roller Systems",
    openGraphDescription: "Modern industrial rollers for paper, steel and textile lines.",
    openGraphImage: "https://indianroller.com/og/home.jpg",
    twitterTitle: "Indian Roller Homepage",
    twitterDescription: "Precision-built roller systems for industrial production.",
    twitterCard: "summary_large_image",
    updatedAt: "2026-03-15T09:20:00.000Z",
  },
  {
    id: "page-2",
    name: "About Us",
    url: "/about",
    status: "complete",
    indexed: true,
    metaTitle: "About Indian Roller | Engineering Excellence",
    metaDescription: "Meet the team behind our polyurethane and rubber roller solutions.",
    keywords: "about indian roller, roller company",
    canonicalUrl: "https://indianroller.com/about",
    robots: "index, follow",
    openGraphTitle: "About Indian Roller",
    openGraphDescription: "See how our production and quality teams work together.",
    openGraphImage: "https://indianroller.com/og/about.jpg",
    twitterTitle: "About Indian Roller",
    twitterDescription: "Built on precision, service and industrial know-how.",
    twitterCard: "summary",
    updatedAt: "2026-03-14T10:15:00.000Z",
  },
  {
    id: "page-3",
    name: "Products",
    url: "/products",
    status: "complete",
    indexed: true,
    metaTitle: "Industrial Roller Products | Indian Roller",
    metaDescription: "Browse rubber, PU, steel and custom-coated rollers.",
    keywords: "roller products, conveyor rollers, pu roller",
    canonicalUrl: "https://indianroller.com/products",
    robots: "index, follow",
    openGraphTitle: "Industrial Roller Products",
    openGraphDescription: "Browse our full roller catalog for major industries.",
    openGraphImage: "https://indianroller.com/og/products.jpg",
    twitterTitle: "Indian Roller Products",
    twitterDescription: "A practical overview of our roller product lines.",
    twitterCard: "summary_large_image",
    updatedAt: "2026-03-12T11:45:00.000Z",
  },
  {
    id: "page-4",
    name: "Textile Rollers",
    url: "/products/textile-rollers",
    status: "incomplete",
    indexed: true,
    metaTitle: "",
    metaDescription: "Specialized rollers designed for textile finishing lines.",
    keywords: "textile roller, finishing rollers",
    canonicalUrl: "https://indianroller.com/products/textile-rollers",
    robots: "index, follow",
    openGraphTitle: "Industrial Roller Products",
    openGraphDescription: "Textile-grade rollers for stable output quality.",
    openGraphImage: "https://indianroller.com/og/textile.jpg",
    twitterTitle: "",
    twitterDescription: "Textile production rollers for consistent performance.",
    twitterCard: "summary",
    updatedAt: "2026-03-16T06:15:00.000Z",
  },
  {
    id: "page-5",
    name: "Paper Rollers",
    url: "/products/paper-rollers",
    status: "complete",
    indexed: false,
    metaTitle: "Paper Industry Rollers | Indian Roller",
    metaDescription: "Reliable paper-processing rollers engineered for durability.",
    keywords: "paper industry rollers, paper machine rollers",
    canonicalUrl: "https://indianroller.com/products/paper-rollers",
    robots: "noindex, follow",
    openGraphTitle: "Paper Industry Rollers | Indian Roller",
    openGraphDescription: "Reliable paper-processing rollers engineered for durability.",
    openGraphImage: "https://indianroller.com/og/paper.jpg",
    twitterTitle: "Paper Industry Rollers",
    twitterDescription: "Reliable paper-processing rollers engineered for durability.",
    twitterCard: "summary",
    updatedAt: "2026-03-11T08:30:00.000Z",
  },
  {
    id: "page-6",
    name: "Blogs",
    url: "/blogs",
    status: "incomplete",
    indexed: true,
    metaTitle: "Industrial Roller Insights | Indian Roller",
    metaDescription: "",
    keywords: "roller blog, industrial insights",
    canonicalUrl: "https://indianroller.com/blogs",
    robots: "index, follow",
    openGraphTitle: "Industrial Roller Insights | Indian Roller",
    openGraphDescription: "",
    openGraphImage: "https://indianroller.com/og/blogs.jpg",
    twitterTitle: "Industrial Roller Insights",
    twitterDescription: "",
    twitterCard: "summary_large_image",
    updatedAt: "2026-03-15T14:05:00.000Z",
  },
  {
    id: "page-7",
    name: "Contact",
    url: "/contact",
    status: "complete",
    indexed: true,
    metaTitle: "Contact Indian Roller",
    metaDescription: "Talk to our team about replacement rollers and custom builds.",
    keywords: "contact indian roller, roller inquiry",
    canonicalUrl: "https://indianroller.com/contact",
    robots: "index, follow",
    openGraphTitle: "Contact Indian Roller",
    openGraphDescription: "Talk to our team about replacement rollers and custom builds.",
    openGraphImage: "https://indianroller.com/og/contact.jpg",
    twitterTitle: "Contact Indian Roller",
    twitterDescription: "Talk to our team about replacement rollers and custom builds.",
    twitterCard: "summary",
    updatedAt: "2026-03-10T12:00:00.000Z",
  },
];

export const initialGlobalSettings: GlobalSettings = {
  defaultMetaTitle: "Indian Roller | Industrial Rollers & Coatings",
  defaultMetaDescription:
    "Indian Roller manufactures industrial roller systems with dependable quality and support.",
  defaultKeywords: "industrial roller, rubber roller, polyurethane roller",
  googleVerification: "google-site-verification=indianroller123456",
  schemaType: "Organization",
  organizationName: "Indian Roller",
  organizationUrl: "https://indianroller.com",
  robotsDefault: "index, follow",
  navbarProductDropdownLimit: 8,
};

export const initialSitemap: SitemapState = {
  lastGenerated: "2026-03-15T08:00:00.000Z",
  autoGenerate: true,
  xml: "",
};

export const initialRedirects: RedirectRule[] = [
  {
    id: "redirect-1",
    from: "/old-products",
    to: "/products",
    type: "301",
    hits: 128,
  },
  {
    id: "redirect-2",
    from: "/blogs/latest-rollers",
    to: "/blogs",
    type: "302",
    hits: 26,
  },
];

export const initialRoles: RolePermission[] = [
  {
    id: "role-1",
    role: "Super Admin",
    dashboard: true,
    pages: true,
    editor: true,
    settings: true,
    sitemap: true,
    redirects: true,
    audit: true,
  },
  {
    id: "role-2",
    role: "SEO Manager",
    dashboard: true,
    pages: true,
    editor: true,
    settings: true,
    sitemap: true,
    redirects: true,
    audit: true,
  },
  {
    id: "role-3",
    role: "Content Editor",
    dashboard: true,
    pages: true,
    editor: true,
    settings: false,
    sitemap: false,
    redirects: false,
    audit: true,
  },
];

export const baseSummaryCards: Omit<SummaryCardData, "value" | "hint">[] = [
  {
    id: "indexed",
    title: "Total Indexed Pages",
    icon: SearchCheck,
    accent: "from-emerald-500 to-teal-500",
  },
  {
    id: "missing",
    title: "Missing Meta Titles",
    icon: AlertTriangle,
    accent: "from-amber-500 to-orange-500",
  },
  {
    id: "duplicate",
    title: "Duplicate Tag Warnings",
    icon: FileSearch,
    accent: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "health",
    title: "SEO Health Score",
    icon: BadgeCheck,
    accent: "from-sky-500 to-indigo-500",
  },
];
